#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom &
polybar wip &
synclient TapButton1=1 TapButton2=3 TapButton3=2 &
synclient VertScrollDelta="-66" &
nm-applet &
kdeconnect-indicator &
fcitx -d &
xset -dpms &
xset s off &
klipper &

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Configs
bspc config border_width         	2
bspc config window_gap         		10
bspc config split_ratio         	0.52
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config single_monocle			false
bspc config ignore_ewmh_focus 		true
bspc config focus_follows_pointer	true
bspc config focused_border_color	"#8caaee"
bspc config normal_border_color		"#616161"
bspc config pointer_action1		move
bspc config pointer_action3		resize_side

for i in {1..10}
do
	bsp-layout set tall $i --master-size 0.52
done

# Rules
# To get app name 
# xprop | grep WM_CLASS
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a krunner border=off
bspc rule -a Blueberry.py state=floating
bspc rule -a plasma.emojier state=floating
bspc rule -a Powermenu state=fullscreen

# Scripts
$HOME/.config/bspwm/scripts/audio.sh
