#! /bin/sh

xrandr -s 1920x1080
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
polybar wip &
nitrogen --restore &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config single_monocle 	 true

bspc config ignore_ewmh_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a kitty desktop='^1'
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Nitrogen state=floating center=true

bspc config focused_border_color "#ff866b"
bspc config normal_border_color "#0496ff"

bspc config pointer_modifier 	mod1
bspc config ponter_action1 	move
bspc config ponter_action3 	resize_side
